// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/hifat/gock/internal/config"
	"github.com/hifat/gock/internal/database"
	"github.com/hifat/gock/internal/handler"
	"github.com/hifat/gock/internal/handler/taskHandler"
	"github.com/hifat/gock/internal/repository/taskRepository"
	"github.com/hifat/gock/internal/service/taskService"
)

// Injectors from wire.go:

func InitializeAPI(config2 config.AppConfig) (Adapter, func()) {
	db, cleanup := database.NewPostgresConnection(config2)
	taskDomainTaskRepository := taskRepository.NewtaskRepository(db)
	taskDomainTaskService := taskService.NewTaskService(taskDomainTaskRepository)
	taskHandlerTaskHandler := taskHandler.NewTaskHandler(taskDomainTaskService)
	handlerHandler := handler.NewHandler(taskHandlerTaskHandler)
	adapter := NewAdapter(handlerHandler)
	return adapter, func() {
		cleanup()
	}
}

// wire.go:

var RepoSet = wire.NewSet(database.NewPostgresDBSet, taskRepository.NewTaskRepoSet)

var ServiceSet = wire.NewSet(taskService.NewTaskServiceSet)

var HandlerSet = wire.NewSet(handler.NewHandlerSet, taskHandler.NewTaskHandlerSet)
