// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/hifat/gock/internal/config"
	"github.com/hifat/gock/internal/database"
	"github.com/hifat/gock/internal/handler"
	"github.com/hifat/gock/internal/handler/helloHandler"
	"github.com/hifat/gock/internal/repository/helloRepository"
	"github.com/hifat/gock/internal/service/helloService"
)

// Injectors from wire.go:

func InitializeAPI(config2 config.AppConfig) (Adapter, func()) {
	db, cleanup := database.NewPostgresConnection(config2)
	helloDomainHelloRepository := helloRepository.NewHelloRepository(db)
	helloDomainHelloService := helloService.NewHelloService(helloDomainHelloRepository)
	helloHandlerHelloHandler := helloHandler.NewHelloHandler(helloDomainHelloService)
	handlerHandler := handler.NewHandler(helloHandlerHelloHandler)
	adapter := NewAdapter(handlerHandler)
	return adapter, func() {
		cleanup()
	}
}

// wire.go:

var RepoSet = wire.NewSet(database.NewPostgresDBSet, helloRepository.NewHelloRepoSet)

var ServiceSet = wire.NewSet(helloService.NewHelloServiceSet)

var HandlerSet = wire.NewSet(handler.NewHandlerSet, helloHandler.NewHelloHandlerSet)
